// <auto-generated />
using System;
using Calendar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Calendar.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthRef");

                    b.HasIndex("PluginId")
                        .HasDatabaseName("IX_Account_PluginId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Account_Priority");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Calendar", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Calendar_AccountId");

                    b.HasIndex("AccountId", "RemoteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Calendar_Account_RemoteId");

                    b.ToTable("Calendar", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsVisible")
                        .HasDatabaseName("IX_Category_IsVisible");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Category_Name");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.DuplicateGroup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalEventId");

                    b.HasIndex("Signature")
                        .IsUnique()
                        .HasDatabaseName("UX_DuplicateGroup_Signature");

                    b.ToTable("DuplicateGroup", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.DuplicateOverride", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("IX_DuplicateOverride_Kind");

                    b.ToTable("DuplicateOverride", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Event", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuplicateGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rrule")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("IX_Event_Recurring")
                        .HasFilter("\"Rrule\" IS NOT NULL");

                    b.HasIndex("DedupSignature")
                        .HasDatabaseName("IX_Event_DedupSignature")
                        .HasFilter("\"DedupSignature\" IS NOT NULL");

                    b.HasIndex("DuplicateGroupId");

                    b.HasIndex("MasterId")
                        .HasDatabaseName("IX_Event_Master")
                        .HasFilter("\"MasterId\" IS NOT NULL");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_Event_PlaceId");

                    b.HasIndex("Uid")
                        .HasDatabaseName("IX_Event_Uid");

                    b.HasIndex("CalendarId", "RemoteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Event_Calendar_RemoteId");

                    b.HasIndex("CalendarId", "StartUtc", "EndUtc")
                        .HasDatabaseName("IX_Event_Calendar_Time");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.EventCategory", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_EventCategory_CategoryId");

                    b.ToTable("EventCategory", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.FareSample", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("FareWatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampledAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FareWatchId", "SampledAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_FareSample_Watch_Time");

                    b.ToTable("FareSample", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.FareWatch", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestPlaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LastLowPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginPlaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pax")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RangeEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RangeStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestPlaceId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FareWatch_IsActive");

                    b.HasIndex("OriginPlaceId");

                    b.ToTable("FareWatch", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.GeocodeCache", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReverse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueryHash")
                        .IsUnique()
                        .HasDatabaseName("UX_GeocodeCache_QueryHash");

                    b.ToTable("GeocodeCache", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Place", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Place_NormalizedKey");

                    b.HasIndex("Lat", "Lng")
                        .HasDatabaseName("IX_Place_LatLng");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Plugin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SdkVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugin", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.PluginConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId")
                        .IsUnique()
                        .HasDatabaseName("UX_PluginConfig_PluginId");

                    b.ToTable("PluginConfig", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.RouteLeg", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComputedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Feasible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geometry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveByUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToEventId");

                    b.HasIndex("FromEventId", "ToEventId", "Mode")
                        .IsUnique()
                        .HasDatabaseName("UX_RouteLeg_From_To_Mode");

                    b.ToTable("RouteLeg", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.ScenarioDraft", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId");

                    b.HasIndex("StartUtc", "EndUtc")
                        .HasDatabaseName("IX_ScenarioDraft_Time");

                    b.ToTable("ScenarioDraft", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.SecretRef", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AuthTag")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("RotatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("IX_SecretRef_Kind");

                    b.ToTable("SecretRef", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Share", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("IX_Share_CalendarId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_Share_Token");

                    b.ToTable("Share", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.SyncState", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackoffUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ctag")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("AccountId", "CalendarId")
                        .IsUnique()
                        .HasDatabaseName("UX_SyncState_Account_Calendar");

                    b.ToTable("SyncState", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc", "EndUtc")
                        .HasDatabaseName("IX_Trip_Time");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.TripItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confirmation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Lamport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectedEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_TripItem_PlaceId");

                    b.HasIndex("ProjectedEventId");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_TripItem_TripId");

                    b.ToTable("TripItem", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.WriteOutbox", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseETag")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnqueuedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EnqueuedAtUtc")
                        .HasDatabaseName("IX_WriteOutbox_Status_Enqueued");

                    b.ToTable("WriteOutbox", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Account", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.SecretRef", null)
                        .WithMany()
                        .HasForeignKey("AuthRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Plugin", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Calendar", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.DuplicateGroup", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("CanonicalEventId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Event", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendar.Domain.Entities.DuplicateGroup", null)
                        .WithMany()
                        .HasForeignKey("DuplicateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Event", "Master")
                        .WithMany("Overrides")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Calendar.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Calendar");

                    b.Navigation("Master");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Calendar.Domain.Entities.EventCategory", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendar.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.FareSample", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.FareWatch", null)
                        .WithMany()
                        .HasForeignKey("FareWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.FareWatch", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("DestPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("OriginPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.PluginConfig", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Plugin", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.RouteLeg", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("FromEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendar.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("ToEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.ScenarioDraft", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Share", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.SyncState", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendar.Domain.Entities.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Calendar.Domain.Entities.TripItem", b =>
                {
                    b.HasOne("Calendar.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("ProjectedEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Calendar.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendar.Domain.Entities.Event", b =>
                {
                    b.Navigation("Overrides");
                });
#pragma warning restore 612, 618
        }
    }
}
